import './globals.css'
import { Provider } from './providers'


export const metadata = {
  title: 'News App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"g-slate-50"}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
